"""The denominator tool, and the two ways it could lie.

WHAT IS BEING GUARDED. `tools/ci/mutation_denominator.py` answers one question:
how many mutants exist, and which of them never reached a verdict. Two failures
would make it worse than nothing, and both are attacked here rather than
assumed away:

    a mutant quietly leaves the count       -> the denominator is a subset again
    a mutant is called `survived` when the
    mutation copy never ran it              -> a fabricated survivor

THE ORACLE IS MUTMUT ITSELF. A resolver checked only against its own reasoning
is unproven, so the falsification half runs a REAL `mutmut run` over a
four-mutant project and then asks the resolver to re-derive the verdicts mutmut
already reached. mutmut says two are killed and two survived; the resolver must
say the same, out of the fork, from nothing but the environment variable. Both
directions matter and each alone proves nothing: a resolver that always answered
`killed` would pass the killed half, and a resolver that never activated the
mutant at all would pass the survived half.

WHY THAT IS NOT A MOCK (§J.6). The mutation copy is generated by mutmut, the
tests are run by pytest in a real subprocess, and the verdicts are compared
against mutmut's own meta store. The only thing this file constructs by hand is
the four-line project under test.

IT NEVER SKIPS. If mutmut cannot run, this file fails. A skip here would be the
exact silent exclusion the tool exists to end.
"""

from __future__ import annotations

import json
import os
import runpy
import shutil
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path

import mutation_denominator as md
import pytest
from authored_source import running_path
from mutmut.__main__ import status_by_exit_code

#: The fixture below writes four mutants: one killed, one survived, one
#: segfaulted, one never run. Named so the assertions read as claims about the
#: fixture rather than as bare integers.
FOUR_MUTANTS = 4
TWO_WITH_NO_VERDICT = 2

#: An exit code mutmut has no entry for, used to prove an unknown status is
#: reported with its number instead of silently becoming `suspicious`.
UNMAPPED_EXIT_CODE = 66

#: pytest's usage-error exit code. Not a verdict about any mutant.
PYTEST_USAGE_ERROR = 4

# ═══════════════════════════════════════════════════════════════════════════
# A mutation copy, built by hand. Real files, real JSON — nothing is patched.
# ═══════════════════════════════════════════════════════════════════════════

#: The generated file's shape, reduced to the one line that matters here: the
#: registration that tells the trampoline a mutant exists. Copied in structure
#: from a real `mutants/src/probe/calc.py`, and proven to match by
#: `test_registration_scan_reads_a_file_mutmut_actually_generated`.
_REGISTRATION_TEMPLATE = "mutants_{function}__mutmut['{name}'] = {name}  # type: ignore\n"


def _write_mutation_copy(
    root: Path,
    source: str,
    exit_code_by_key: dict[str, int | None],
    *,
    register: Sequence[str] | None = None,
) -> Path:
    """Write a `mutants/` tree recording `exit_code_by_key` for `source`.

    `register` names the mutants the generated file claims to define; it
    defaults to all of them, so the deliberately-stale case has to be asked for.
    """
    mutants_dir = root / "mutants"
    generated = mutants_dir / source
    generated.parent.mkdir(parents=True, exist_ok=True)
    names = list(exit_code_by_key) if register is None else list(register)
    generated.write_text(
        "".join(
            _REGISTRATION_TEMPLATE.format(
                function=md.mangled_name(name).rpartition(".")[2], name=md.generated_function(name)
            )
            for name in names
        ),
        encoding="utf-8",
    )
    meta = generated.with_suffix(generated.suffix + ".meta")
    meta.write_text(
        json.dumps(
            {
                "exit_code_by_key": exit_code_by_key,
                "hash_by_function_name": {},
                "type_check_error_by_key": {},
                "durations_by_key": {},
                "estimated_durations_by_key": {},
            }
        ),
        encoding="utf-8",
    )
    return mutants_dir


def _write_stats(mutants_dir: Path, tests_by_function: dict[str, list[str]]) -> None:
    (mutants_dir / md.STATS_FILENAME).write_text(
        json.dumps({"tests_by_mangled_function_name": tests_by_function}), encoding="utf-8"
    )


#: One killed, one survived, one segfaulted, one never run. The segfault and the
#: never-run mutant are the population the mutation score silently drops.
_FOUR_OUTCOMES = {
    "probe.calc.x_add__mutmut_1": 1,
    "probe.calc.x_add__mutmut_2": 0,
    "probe.calc.x_add__mutmut_3": -11,
    "probe.calc.x_add__mutmut_4": None,
}


# ═══════════════════════════════════════════════════════════════════════════
# The denominator. Everything mutmut generated, whatever became of it.
# ═══════════════════════════════════════════════════════════════════════════


def test_a_segfaulted_and_an_unrun_mutant_stay_in_the_denominator(tmp_path: Path) -> None:
    """THE DEFECT, stated as an assertion (F-007).

    `killed + survived` is 2 here and the tree contains 4. A tool that agreed
    with the gate would report 2 and this repository would keep believing a
    score taken over half its mutants.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))

    mutants = md.read_mutants(mutants_dir)

    assert len(mutants) == FOUR_MUTANTS, "the denominator is every mutant, not the scoreable ones"
    assert {mutant.status for mutant in mutants} == {
        "killed",
        "survived",
        "segfault",
        "not checked",
    }


def test_every_mutant_with_no_verdict_is_named_not_just_counted(tmp_path: Path) -> None:
    """A count says the measurement shrank. A name says which line stopped being
    measured, and only the second is actionable.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))

    silent = md.without_verdict(md.read_mutants(mutants_dir))

    assert [mutant.name for mutant in silent] == [
        "probe.calc.x_add__mutmut_3",
        "probe.calc.x_add__mutmut_4",
    ]
    printed = "\n".join(md.report(md.read_mutants(mutants_dir)))
    assert "probe.calc.x_add__mutmut_3" in printed
    assert "probe.calc.x_add__mutmut_4" in printed
    assert "segfault" in printed


def test_the_tally_itemises_the_excluded_bucket_by_status(tmp_path: Path) -> None:
    """`4 not scoreable` is a number to argue with. `segfault=1, not checked=1`
    is a diagnosis, and the two failures have completely different fixes.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))

    (tally,) = md.tally_by_source(md.read_mutants(mutants_dir))

    assert tally.source == "src/probe/calc.py"
    assert (tally.generated, tally.killed, tally.survived) == (FOUR_MUTANTS, 1, 1)
    assert tally.no_verdict == {"segfault": 1, "not checked": 1}
    assert tally.no_verdict_total == TWO_WITH_NO_VERDICT


def test_two_source_files_are_tallied_separately(tmp_path: Path) -> None:
    """A per-file report is the whole request. One combined row would hide a
    single module that segfaults entirely inside a healthy total.
    """
    _write_mutation_copy(tmp_path, "src/probe/calc.py", {"probe.calc.x_add__mutmut_1": 1})
    mutants_dir = _write_mutation_copy(
        tmp_path, "src/probe/other.py", {"probe.other.x_f__mutmut_1": -11}
    )

    tallies = md.tally_by_source(md.read_mutants(mutants_dir))

    assert [(t.source, t.generated, t.no_verdict_total) for t in tallies] == [
        ("src/probe/calc.py", 1, 0),
        ("src/probe/other.py", 1, 1),
    ]


def test_an_exit_code_mutmut_has_never_seen_is_reported_with_its_number(tmp_path: Path) -> None:
    """mutmut's status table is a `defaultdict` returning `suspicious`, so a new
    exit code arrives wearing an old name. This keeps the number attached.
    """
    mutants_dir = _write_mutation_copy(
        tmp_path, "src/probe/calc.py", {"probe.calc.x_a__mutmut_1": UNMAPPED_EXIT_CODE}
    )

    (mutant,) = md.read_mutants(mutants_dir)

    assert mutant.status == "suspicious"
    assert mutant.status_was_defaulted is True
    assert "66" in mutant.describe()
    assert "UNKNOWN TO MUTMUT" in mutant.describe()


def test_asking_about_an_unknown_exit_code_does_not_grow_mutmuts_table() -> None:
    """A `defaultdict` INSERTS on a missing lookup. Reading it with `[]` would
    make this module quietly rewrite the tool it is measuring, and the second
    read of the same code would then claim mutmut had always known it.
    """
    never_used = 4242
    assert never_used not in status_by_exit_code, "precondition: a code mutmut has no entry for"

    status, defaulted = md.status_for(never_used)

    assert (status, defaulted) == ("suspicious", True)
    assert never_used not in status_by_exit_code, "reading the table must not extend it"


def test_a_known_exit_code_is_not_reported_as_a_guess() -> None:
    """The other direction. Without it, a function that always answered
    "defaulted" would pass the test above and label every real status a guess.
    """
    assert md.status_for(1) == ("killed", False)
    assert md.status_for(0) == ("survived", False)
    assert md.status_for(-11) == ("segfault", False)
    assert md.status_for(None) == ("not checked", False)


# ═══════════════════════════════════════════════════════════════════════════
# Failing loudly. Every one of these would otherwise be an empty, passing table.
# ═══════════════════════════════════════════════════════════════════════════


def test_an_absent_mutation_copy_is_an_error_and_not_an_empty_tally(tmp_path: Path) -> None:
    """HOLLOW-GATE DEFENCE. Zero mutants and zero exclusions is a perfect
    report. It is also what a tool pointed at nothing produces.
    """
    with pytest.raises(md.MutationResultsUnavailableError, match="not a directory"):
        md.read_mutants(tmp_path / "mutants")


def test_a_mutation_copy_with_no_results_is_an_error(tmp_path: Path) -> None:
    (tmp_path / "mutants").mkdir()

    with pytest.raises(md.MutationResultsUnavailableError, match="no mutants recorded"):
        md.read_mutants(tmp_path / "mutants")


def test_a_meta_file_that_records_no_verdicts_is_an_error(tmp_path: Path) -> None:
    meta = tmp_path / "mutants" / "src" / "probe" / "calc.py.meta"
    meta.parent.mkdir(parents=True)
    meta.write_text(json.dumps({"durations_by_key": {}}), encoding="utf-8")

    with pytest.raises(md.MutationResultsUnavailableError, match="exit_code_by_key"):
        md.read_mutants(tmp_path / "mutants")


def test_a_truncated_meta_file_is_an_error_not_a_smaller_denominator(tmp_path: Path) -> None:
    """A half-written JSON file is exactly how a killed run leaves the tree, and
    treating it as "this file had no mutants" is the failure in miniature.
    """
    meta = tmp_path / "mutants" / "src" / "probe" / "calc.py.meta"
    meta.parent.mkdir(parents=True)
    meta.write_text('{"exit_code_by_key": {"a__mutmut_1"', encoding="utf-8")

    with pytest.raises(md.MutationResultsUnavailableError, match="not valid JSON"):
        md.read_mutants(tmp_path / "mutants")


def test_the_covering_tests_are_read_back_sorted_and_whole(tmp_path: Path) -> None:
    """Sorted because the order tests run in must not depend on JSON key order:
    a verdict that changes between runs of the same commit is not a measurement.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))
    _write_stats(mutants_dir, {"probe.calc.x_add": ["t.py::b", "t.py::a"]})

    covering = md.read_covering_tests(mutants_dir)

    assert covering == {"probe.calc.x_add": ("t.py::a", "t.py::b")}


def test_a_stats_file_with_no_associations_is_an_error(tmp_path: Path) -> None:
    """An empty association map makes every mutant look like nothing covers it,
    which reads as a test-suite defect rather than a missing measurement.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))
    (mutants_dir / md.STATS_FILENAME).write_text(json.dumps({"duration_by_test": {}}), "utf-8")

    with pytest.raises(md.MutationResultsUnavailableError, match="tests_by_mangled_function_name"):
        md.read_covering_tests(mutants_dir)


def test_a_meta_file_holding_something_other_than_an_object_is_an_error(tmp_path: Path) -> None:
    """Valid JSON that is not a mapping. `.get` on a list raises AttributeError
    deep inside the walk, which reads as a tool bug rather than a bad file.
    """
    meta = tmp_path / "mutants" / "src" / "probe" / "calc.py.meta"
    meta.parent.mkdir(parents=True)
    meta.write_text("[]", encoding="utf-8")

    with pytest.raises(md.MutationResultsUnavailableError, match="not a JSON object"):
        md.read_mutants(tmp_path / "mutants")


def test_an_unreadable_mutated_file_is_an_error_not_an_empty_registration_set(
    tmp_path: Path,
) -> None:
    """An empty set would make EVERY mutant look absent from the copy — a
    plausible-looking report produced by a missing file (Law 11).
    """
    with pytest.raises(md.MutationResultsUnavailableError, match="could not be read"):
        md.registered_mutants(tmp_path / "nowhere" / "calc.py")


def test_a_missing_stats_file_is_an_error_not_an_empty_test_map(tmp_path: Path) -> None:
    """An empty map makes every mutant look like "no test covers this", which
    reads as a test-suite defect rather than a missing file.
    """
    (tmp_path / "mutants").mkdir()

    with pytest.raises(md.MutationResultsUnavailableError, match="could not be read"):
        md.read_covering_tests(tmp_path / "mutants")


def test_a_name_that_is_not_a_mutant_name_is_refused(tmp_path: Path) -> None:
    """`mangled_name` returning the string whole would look up an empty test set,
    and an empty test set is indistinguishable from "nothing covers this".
    """
    del tmp_path
    with pytest.raises(md.MutationResultsUnavailableError, match="not a mutant name"):
        md.mangled_name("accountant_dad.confidence.score")


# ═══════════════════════════════════════════════════════════════════════════
# Resolution, with the process edge faked and nothing else (§J.7).
# ═══════════════════════════════════════════════════════════════════════════


def _mutant(name: str = "probe.calc.x_add__mutmut_3", status: str = "segfault") -> md.Mutant:
    return md.Mutant(
        name=name,
        source="src/probe/calc.py",
        exit_code=-11,
        status=status,
        status_was_defaulted=False,
    )


def _copy_registering(tmp_path: Path, *names: str) -> Path:
    return _write_mutation_copy(
        tmp_path, "src/probe/calc.py", dict.fromkeys(names, -11), register=names
    )


def test_a_no_verdict_mutant_whose_tests_fail_out_of_the_fork_is_killed(tmp_path: Path) -> None:
    mutants_dir = _copy_registering(tmp_path, "probe.calc.x_add__mutmut_3")

    (resolution,) = md.resolve(
        [_mutant()],
        {"probe.calc.x_add": ("tests/test_calc.py::test_add",)},
        mutants_dir,
        lambda _mutant, _tests: 1,
    )

    assert (resolution.verdict, resolution.resolved) == ("killed", True)
    assert resolution.test_count == 1


def test_a_no_verdict_mutant_whose_tests_pass_out_of_the_fork_is_a_true_survivor(
    tmp_path: Path,
) -> None:
    """The half that matters most. These are the mutants reported as no-verdict
    that are in fact ALIVE — a real hole in the suite, hidden by a crash.
    """
    mutants_dir = _copy_registering(tmp_path, "probe.calc.x_add__mutmut_3")

    (resolution,) = md.resolve(
        [_mutant()],
        {"probe.calc.x_add": ("tests/test_calc.py::test_add",)},
        mutants_dir,
        lambda _mutant, _tests: 0,
    )

    assert (resolution.verdict, resolution.resolved) == ("survived", True)


def test_a_mutant_the_mutation_copy_does_not_register_is_never_called_a_survivor(
    tmp_path: Path,
) -> None:
    """THE FALSE SURVIVOR, TRAPPED. The trampoline calls the ORIGINAL function
    for a name it does not know, so the tests pass, pytest exits 0, and an
    unguarded resolver reads that as "alive". Measured on a real mutation copy
    before this guard existed: `probe.calc.x_add__mutmut_9999` resolved to
    `survived`.

    The runner here would answer 0 — "everything passed". The guard must reach
    its verdict without ever asking it.
    """
    mutants_dir = _copy_registering(tmp_path, "probe.calc.x_add__mutmut_1")
    asked: list[str] = []

    def runner(mutant: md.Mutant, _tests: Sequence[str]) -> int:
        asked.append(mutant.name)
        return 0

    (resolution,) = md.resolve(
        [_mutant(name="probe.calc.x_add__mutmut_9999")],
        {"probe.calc.x_add": ("tests/test_calc.py::test_add",)},
        mutants_dir,
        runner,
    )

    assert resolution.verdict == "not in mutation copy"
    assert resolution.resolved is False
    assert "ORIGINAL function" in resolution.reason
    assert asked == [], "a mutant that cannot be activated must not be run at all"


def test_a_mutant_with_no_covering_test_is_reported_and_not_guessed_at(tmp_path: Path) -> None:
    """ "No test failed" and "no test ran" are the same exit code and opposite
    facts. Calling the second one `survived` would invent a verdict (Law 24).
    """
    mutants_dir = _copy_registering(tmp_path, "probe.calc.x_add__mutmut_3")

    (resolution,) = md.resolve([_mutant()], {}, mutants_dir, lambda _mutant, _tests: 0)

    assert resolution.verdict == "no tests"
    assert resolution.resolved is False
    assert resolution.exit_code is None
    assert "no test covering" in resolution.reason


def test_an_exit_code_that_is_not_a_verdict_stays_unresolved_and_names_the_number(
    tmp_path: Path,
) -> None:
    """pytest exits 4 on a usage error and 2 on an interrupt. Neither means the
    mutant lived or died, and folding either into a column would be a guess.
    """
    mutants_dir = _copy_registering(tmp_path, "probe.calc.x_add__mutmut_3")

    (resolution,) = md.resolve(
        [_mutant()],
        {"probe.calc.x_add": ("tests/test_calc.py::test_add",)},
        mutants_dir,
        lambda _mutant, _tests: PYTEST_USAGE_ERROR,
    )

    assert resolution.resolved is False
    assert "pytest exited 4" in resolution.reason
    assert "4" in resolution.describe()


def test_resolution_runs_exactly_the_tests_mutmut_associated_with_the_mutant(
    tmp_path: Path,
) -> None:
    """Running the whole suite instead would answer a different question, take
    hours, and turn any unrelated failure into a kill.
    """
    mutants_dir = _copy_registering(tmp_path, "probe.calc.x_add__mutmut_3")
    seen: list[tuple[str, tuple[str, ...]]] = []

    def runner(mutant: md.Mutant, tests: Sequence[str]) -> int:
        seen.append((mutant.name, tuple(tests)))
        return 1

    md.resolve(
        [_mutant()],
        {
            "probe.calc.x_add": ("tests/test_calc.py::test_add",),
            "probe.calc.x_clamp": ("tests/test_calc.py::test_clamp",),
        },
        mutants_dir,
        runner,
    )

    assert seen == [("probe.calc.x_add__mutmut_3", ("tests/test_calc.py::test_add",))]


def test_a_resolved_mutant_is_re_tallied_under_its_true_verdict(tmp_path: Path) -> None:
    """THE COLUMN THE WHOLE EXERCISE IS FOR. A segfaulted mutant that turns out
    to be alive belongs in `survived` for its module, not in a footnote — that
    is a real hole in the suite that the score never saw.

    Counted by substituting the verdict and re-running the SAME tally, so the
    two tables can never disagree with each other (Law 14).
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))
    mutants = md.read_mutants(mutants_dir)
    resolutions = md.resolve(
        md.without_verdict(mutants),
        {"probe.calc.x_add": ("t.py::a",)},
        mutants_dir,
        lambda _mutant, _tests: md.PYTEST_ALL_PASSED,
    )

    (before,) = md.tally_by_source(mutants)
    (after,) = md.tally_by_source(md.with_resolutions(mutants, resolutions))

    assert (before.killed, before.survived, before.no_verdict_total) == (1, 1, 2)
    assert (after.killed, after.survived, after.no_verdict_total) == (1, 3, 0)
    assert after.generated == before.generated == FOUR_MUTANTS, "the denominator never moves"


def test_an_unresolved_mutant_keeps_its_no_verdict_status_in_the_true_table(
    tmp_path: Path,
) -> None:
    """The other direction, and the one that could quietly launder a failure: a
    mutant that STILL has no verdict must not drift into a scoreable column.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))
    mutants = md.read_mutants(mutants_dir)
    resolutions = md.resolve(
        md.without_verdict(mutants), {}, mutants_dir, lambda _mutant, _tests: 0
    )

    (after,) = md.tally_by_source(md.with_resolutions(mutants, resolutions))

    assert (after.killed, after.survived) == (1, 1)
    assert after.no_verdict == {"no tests": 2}


def test_a_mutant_nobody_re_ran_is_left_exactly_as_mutmut_recorded_it(tmp_path: Path) -> None:
    """`with_resolutions` substitutes; it must never invent. A mutant with no
    resolution keeps mutmut's own verdict and exit code untouched.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))
    mutants = md.read_mutants(mutants_dir)

    unchanged = md.with_resolutions(mutants, [])

    assert unchanged == mutants


# ═══════════════════════════════════════════════════════════════════════════
# The command line. Completeness, never a threshold.
# ═══════════════════════════════════════════════════════════════════════════


def test_the_cli_fails_while_any_mutant_has_no_verdict(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))

    code = md.cli(["mutation_denominator.py", "--mutants-dir", str(tmp_path / "mutants")])

    assert code == 1
    printed = capsys.readouterr().out
    assert "2 of 4 mutants have NO VERDICT" in printed


def test_the_cli_passes_only_when_every_mutant_has_a_verdict(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The other direction. A tool that always failed would satisfy the test
    above and could never certify anything."""
    _write_mutation_copy(
        tmp_path,
        "src/probe/calc.py",
        {"probe.calc.x_add__mutmut_1": 1, "probe.calc.x_add__mutmut_2": 0},
    )

    code = md.cli(["mutation_denominator.py", "--mutants-dir", str(tmp_path / "mutants")])

    assert code == 0
    assert "every one of 2 mutants has a verdict" in capsys.readouterr().out


def test_an_unrecognised_argument_is_refused(tmp_path: Path) -> None:
    del tmp_path
    with pytest.raises(SystemExit, match="usage:"):
        md.parse_argv(["mutation_denominator.py", "--score"])
    with pytest.raises(SystemExit, match="usage:"):
        md.parse_argv(["mutation_denominator.py", "--mutants-dir"])


def test_the_two_flags_are_read_and_default_to_the_mutation_copy() -> None:
    """`--resolve` is off by default: re-running mutants starts processes, and a
    reporting tool must not do that because somebody forgot a flag.
    """
    assert md.parse_argv(["mutation_denominator.py"]) == md.Options(
        mutants_dir=Path("mutants"), resolve=False
    )
    assert md.parse_argv(["mutation_denominator.py", "--resolve", "--mutants-dir", "x"]) == (
        md.Options(mutants_dir=Path("x"), resolve=True)
    )


def test_the_report_shows_a_per_module_true_survivor_table_once_resolved(
    tmp_path: Path,
) -> None:
    """The requested shape of the answer: per module, after resolution, with the
    unresolved remainder still named underneath rather than rounded away.
    """
    mutants_dir = _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))
    mutants = md.read_mutants(mutants_dir)
    resolutions = md.resolve(
        md.without_verdict(mutants),
        {"probe.calc.x_add": ("t.py::a",)},
        mutants_dir,
        lambda mutant, _tests: (
            md.PYTEST_ALL_PASSED if mutant.name.endswith("_3") else PYTEST_USAGE_ERROR
        ),
    )

    printed = "\n".join(md.report(mutants, resolutions))

    assert "PER MODULE AFTER RESOLUTION" in printed
    assert "still no verdict after resolution: 1" in printed
    assert "probe.calc.x_add__mutmut_4" in printed


def test_the_module_runs_as_a_script_and_exits_with_its_own_verdict(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """CI runs `python3 tools/ci/mutation_denominator.py`, not `cli()`. The argv
    dispatch and the `__main__` block are what actually execute, so they are
    tested by executing them (mirrors `tests/unit/test_cli_entrypoints.py`).
    """
    _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))
    monkeypatch.setattr(
        sys, "argv", ["mutation_denominator.py", "--mutants-dir", str(tmp_path / "mutants")]
    )

    with pytest.raises(SystemExit) as raised:
        runpy.run_path(str(running_path(md)), run_name="__main__")

    assert raised.value.code == 1


def test_the_report_prints_no_percentage(tmp_path: Path) -> None:
    """ONE SOURCE OF TRUTH (Law 19). `.github/workflows/testing.yml` owns the
    mutation score. A second number computed here could differ from it, and two
    disagreeing scores are worse than one incomplete one.
    """
    _write_mutation_copy(tmp_path, "src/probe/calc.py", dict(_FOUR_OUTCOMES))

    printed = "\n".join(md.report(md.read_mutants(tmp_path / "mutants")))

    assert "%" not in printed


# ═══════════════════════════════════════════════════════════════════════════
# FALSIFICATION. A real mutmut run is the oracle; the resolver must match it.
# ═══════════════════════════════════════════════════════════════════════════

_PROJECT = "[tool.pytest.ini_options]\ntestpaths = ['tests']\npythonpath = ['src']\n"
_MUTMUT_CONFIG = "[tool.mutmut]\nsource_paths = ['src']\nalso_copy = ['pyproject.toml']\n"
#: `add` is fully caught; `clamp`'s boundary mutants are not. Chosen so a real
#: run yields BOTH verdicts — an oracle that only ever said `killed` would let a
#: resolver that always answered `killed` through.
_CALC = (
    "def add(a, b):\n    return a + b\n\n\n"
    "def clamp(x):\n    if x > 0:\n        return x\n    return 0\n"
)
_CALC_TESTS = (
    "from probe.calc import add, clamp\n\n\n"
    "def test_add():\n    assert add(1, 2) == 3\n\n\n"
    "def test_clamp():\n    assert clamp(5) == 5\n    assert clamp(-1) == 0\n"
)


def _mutmut_environment() -> dict[str, str]:
    """A clean environment for a nested mutmut run.

    `MUTANT_UNDER_TEST` is removed because this file itself runs under mutation:
    inheriting `stats` or a live mutant name would make the nested run measure
    the outer run's state. `no_proxy` is set for the reason the whole exercise
    exists — `getproxies_macosx_sysconf()` is not fork-safe, and mutmut forks.
    """
    environment = {key: value for key, value in os.environ.items() if key != md.MUTANT_ENV_VAR}
    environment.update(md.NO_PROXY_ENVIRONMENT)
    return environment


@pytest.fixture(scope="session")
def real_mutmut_run(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A genuine `mutmut run` over four mutants. Returns its `mutants/` directory.

    Session-scoped because the run costs a real process; every test below reads
    the same result, exactly as a human would read one run's output.
    """
    project = tmp_path_factory.mktemp("mutmut_oracle")
    (project / "pyproject.toml").write_text(_PROJECT + "\n" + _MUTMUT_CONFIG, encoding="utf-8")
    (project / "src" / "probe").mkdir(parents=True)
    (project / "src" / "probe" / "__init__.py").write_text("", encoding="utf-8")
    (project / "src" / "probe" / "calc.py").write_text(_CALC, encoding="utf-8")
    (project / "tests").mkdir()
    (project / "tests" / "test_calc.py").write_text(_CALC_TESTS, encoding="utf-8")

    completed = subprocess.run(  # noqa: S603 - argv list, no shell, interpreter is sys.executable
        [sys.executable, "-m", "mutmut", "run"],
        check=False,
        cwd=project,
        env=_mutmut_environment(),
        capture_output=True,
        text=True,
    )
    # NEVER a skip. A resolver whose oracle did not run is a resolver nothing
    # checked, and reporting that as "passed" is this repository's own F-029.
    assert completed.returncode == 0, (
        "the oracle `mutmut run` failed, so nothing below proves anything:\n"
        f"{completed.stdout[-4000:]}\n{completed.stderr[-4000:]}"
    )
    return project / "mutants"


def test_the_oracle_produced_both_verdicts(real_mutmut_run: Path) -> None:
    """PRECONDITION for the two tests below, asserted rather than assumed.

    If this project ever stopped producing both a killed and a surviving mutant,
    the agreement tests would still pass while checking only one direction.
    """
    statuses = {mutant.name: mutant.status for mutant in md.read_mutants(real_mutmut_run)}

    assert sorted(statuses.values()).count("killed") >= 1
    assert sorted(statuses.values()).count("survived") >= 1
    assert len(statuses) == FOUR_MUTANTS, f"expected four mutants here, got {statuses}"


def test_the_resolver_reaches_mutmuts_own_verdict_on_every_mutant(real_mutmut_run: Path) -> None:
    """THE FALSIFICATION. Known answers, both directions, from an independent
    oracle — mutmut's forked child — re-derived by an `exec`'d subprocess that
    shares none of the fork's state.

    A resolver that never activated the mutant would report every one of these
    as `survived` and fail on the killed ones. A resolver that broke the test
    run would report every one as `killed` and fail on the survivors. Only a
    resolver that actually activates the right mutant passes both.
    """
    covering = md.read_covering_tests(real_mutmut_run)
    disagreements: list[str] = []

    for mutant in md.read_mutants(real_mutmut_run):
        tests = covering[md.mangled_name(mutant.name)]
        exit_code = md.run_covering_tests(mutant, tests, real_mutmut_run)
        verdict, _ = md.verdict_from_exit_code(exit_code)
        if verdict != mutant.status:
            disagreements.append(f"{mutant.name}: mutmut={mutant.status} resolver={verdict}")

    assert disagreements == [], "the out-of-fork resolver contradicted mutmut:\n" + "\n".join(
        disagreements
    )


def test_the_resolver_reads_the_instrumented_tree_and_not_the_pristine_one(
    real_mutmut_run: Path,
) -> None:
    """The sharpest single check in this file.

    With NO mutant active every test passes. With mutmut's own killed mutant
    active the same command must fail. If `run_covering_tests` were reaching the
    authored `src/` instead of `mutants/src/`, both runs would pass — and every
    resolved mutant in this repository would be a fabricated survivor.
    """
    mutants = md.read_mutants(real_mutmut_run)
    covering = md.read_covering_tests(real_mutmut_run)
    killed = next(mutant for mutant in mutants if mutant.status == "killed")
    tests = covering[md.mangled_name(killed.name)]

    inactive = md.Mutant(
        name=killed.name.rpartition(md.MUTANT_INDEX_SEPARATOR)[0] + md.MUTANT_INDEX_SEPARATOR + "0",
        source=killed.source,
        exit_code=None,
        status="not checked",
        status_was_defaulted=False,
    )

    assert md.run_covering_tests(inactive, tests, real_mutmut_run) == md.PYTEST_ALL_PASSED
    assert md.run_covering_tests(killed, tests, real_mutmut_run) == md.PYTEST_TESTS_FAILED


def test_registration_scan_reads_a_file_mutmut_actually_generated(real_mutmut_run: Path) -> None:
    """The stale-copy guard is only worth anything if it can parse mutmut's real
    output. Asserting it against a hand-written fixture would prove the fixture.
    """
    recorded = {md.generated_function(mutant.name) for mutant in md.read_mutants(real_mutmut_run)}

    registered = md.registered_mutants(real_mutmut_run / "src" / "probe" / "calc.py")

    assert recorded <= registered, (
        f"meta records mutants the file does not define: {recorded - registered}"
    )
    assert "_mutmut_orig" in registered, "precondition: mutmut registers the original alongside"


def test_a_crash_written_over_a_real_verdict_is_recovered_end_to_end(
    real_mutmut_run: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """THE WHOLE EXERCISE, IN ONE TEST, ON REAL MUTMUT OUTPUT.

    Take a mutant mutmut reached a verdict on, overwrite that verdict with a
    segfault — the exact corruption F-007 describes — and run the CLI with
    `--resolve`. The out-of-fork re-run must recover the verdict mutmut
    originally had, and the CLI must then certify the denominator complete.

    The oracle tree is COPIED first: mutating the session fixture would leave
    every later test reading a result this test invented.
    """
    copied = tmp_path / "mutants"
    shutil.copytree(real_mutmut_run, copied)
    meta = next(copied.rglob("*.py.meta"))
    recorded = json.loads(meta.read_text(encoding="utf-8"))
    victim = next(name for name, code in recorded["exit_code_by_key"].items() if code is not None)
    original_verdict = md.status_for(recorded["exit_code_by_key"][victim])[0]
    recorded["exit_code_by_key"][victim] = -11
    meta.write_text(json.dumps(recorded), encoding="utf-8")

    assert any(m.status == "segfault" for m in md.read_mutants(copied)), (
        "precondition: the corruption must be visible before it is repaired"
    )

    corrupted = md.read_mutants(copied)
    resolutions = md.resolve(
        md.without_verdict(corrupted),
        md.read_covering_tests(copied),
        copied,
        lambda mutant, tests: md.run_covering_tests(mutant, tests, copied),
    )

    # BIT FOR BIT. Not "close to", not "also has a verdict" — the recovered
    # table must be the table that existed before the crash was written over it.
    assert md.tally_by_source(md.with_resolutions(corrupted, resolutions)) == md.tally_by_source(
        md.read_mutants(real_mutmut_run)
    )
    assert [resolution.verdict for resolution in resolutions] == [original_verdict]

    code = md.cli(["mutation_denominator.py", "--resolve", "--mutants-dir", str(copied)])

    printed = capsys.readouterr().out
    assert code == 0, printed
    assert "still no verdict after resolution: 0" in printed
    assert "every one of 4 mutants has a verdict" in printed


def test_the_whole_pipeline_runs_on_a_real_run_and_finds_nothing_missing(
    real_mutmut_run: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """END TO END, on real mutmut output. This project has no crashes, so every
    mutant has a verdict and the CLI must certify exactly that. It is the
    negative control for `test_the_cli_fails_while_any_mutant_has_no_verdict`:
    together they prove the exit code tracks the tree rather than a constant.
    """
    code = md.cli(["mutation_denominator.py", "--mutants-dir", str(real_mutmut_run)])

    printed = capsys.readouterr().out
    assert code == 0, printed
    assert "TRUE DENOMINATOR (mutants generated) : 4" in printed
    assert "src/probe/calc.py" in printed
