"""Source-reading discipline: a test may only assert about AUTHORED source.

Two things live here, and they are two halves of one guard.

The first half tests `tools/ci/authored_source.py` itself — including a
reproduction of the exact failure that killed the `mutation` gate on
`a501a69`, built from mutmut's real dispatcher text rather than a paraphrase
of it.

The second half is the validator: an AST scan over every file under `tests/`
that refuses `inspect.getsource` and its four siblings, and refuses reading a
module's file through its own `__file__`. Both forms answer *"what is this
interpreter running"* when the question asked was *"what did we write"*. Under
mutation those differ, and the difference has now cost two separate gate
failures — one loud, one silent.

WHY A VALIDATOR AND NOT A FIX. The five instances found so far were each found
by a CI job that takes 3h21m when it succeeds, one at a time, months apart.
The class cannot be policed by remembering it. It can be policed by a test that
runs in milliseconds and names the file and line.
"""

from __future__ import annotations

import ast
import pathlib
from types import ModuleType
from typing import TypeGuard

import pytest
from authored_source import (
    AuthoredSourceUnavailableError,
    authored_function_source,
    authored_path,
    authored_source,
    authored_tree,
)

from accountant_dad.engines.input_engine import assembly as assembly_module

# ═══════════════════════════════════════════════════════════════════════════
# mutmut's real dispatcher, copied character for character out of
# `mutants/src/accountant_dad/engines/input_engine/assembly.py` as generated by
# mutmut 3.3.1. Written out rather than referenced so this test keeps failing
# for the right reason on a machine where mutation cannot run at all (F-016).
# ═══════════════════════════════════════════════════════════════════════════
MUTMUT_DISPATCHER = '''
def _mutmut_trampoline(orig, mutants, call_args, call_kwargs, self_arg = None):
    """Forward call to original or mutated function, depending on the environment"""
    import os
    mutant_under_test = os.environ['MUTANT_UNDER_TEST']
    if mutant_under_test == 'fail':
        from mutmut.__main__ import MutmutProgrammaticFailException
        raise MutmutProgrammaticFailException('Failed programmatically')
    elif mutant_under_test == 'stats':
        from mutmut.__main__ import record_trampoline_hit
        record_trampoline_hit(orig.__module__ + '.' + orig.__name__)
        result = orig(*call_args, **call_kwargs)
        return result
'''

AUTHORED_BODY = '''\
"""The authored module."""


def combine(left: object | None, right: object | None) -> list[object]:
    """Compares against None and nothing else."""
    return [value for value in (left, right) if value is not None]


def helper() -> int:
    def combine() -> int:
        return 1

    return combine()
'''


def _module_from(path: pathlib.Path) -> ModuleType:
    """A real module object claiming to come from `path`.

    A duck-typed stand-in does not work: `inspect.getfile` rejects anything
    that is not genuinely a module, class, method, function, traceback, frame
    or code object. Using the real type is also what the production callers
    pass, so the test exercises the same path they do.
    """
    module = ModuleType("stub_module")
    module.__file__ = str(path)
    return module


# ═══════════════════════════════════════════════════════════════════════════
# The regression. This is the failure that produced `4075 not checked`.
# ═══════════════════════════════════════════════════════════════════════════


def test_the_mutation_gate_failure_does_not_recur(tmp_path: pathlib.Path) -> None:
    """A module imported out of `mutants/` yields the AUTHORED text.

    Reproduces `test_assembly_compares_only_against_none` exactly: parse what
    the reader returns, collect every `ast.Compare` that compares against
    something other than `None`, and require the list to be empty. Against the
    instrumented file that list is `[(…, 'fail'), (…, 'stats')]` — mutmut's
    own comparisons, attributed to this repository.
    """
    authored = tmp_path / "src" / "pkg" / "thing.py"
    authored.parent.mkdir(parents=True)
    authored.write_text(AUTHORED_BODY, encoding="utf-8")

    instrumented = tmp_path / "mutants" / "src" / "pkg" / "thing.py"
    instrumented.parent.mkdir(parents=True)
    instrumented.write_text(AUTHORED_BODY + MUTMUT_DISPATCHER, encoding="utf-8")

    # What the old code did, spelled out, so the contrast is not a claim.
    running_text = instrumented.read_text(encoding="utf-8")
    running_comparisons = [
        node.lineno
        for node in ast.walk(ast.parse(running_text))
        if isinstance(node, ast.Compare)
        and not all(
            isinstance(comparator, ast.Constant) and comparator.value is None
            for comparator in node.comparators
        )
    ]
    assert running_comparisons, (
        "precondition failed: the fixture must contain the comparisons that "
        "broke the gate, otherwise this test proves nothing"
    )

    text = authored_source(_module_from(instrumented))
    comparisons = [
        node.lineno
        for node in ast.walk(ast.parse(text))
        if isinstance(node, ast.Compare)
        and not all(
            isinstance(comparator, ast.Constant) and comparator.value is None
            for comparator in node.comparators
        )
    ]
    assert comparisons == [], f"authored source still carries instrumentation at {comparisons}"
    assert "MUTANT_UNDER_TEST" not in text
    assert "'stats'" not in text


def test_no_module_in_this_package_reports_instrumented_source() -> None:
    """The invariant, asserted over every module rather than one.

    Trivially true off mutation and the entire point under it: if the redirect
    ever stops working, this goes red for thirty-three modules at once instead
    of for whichever one happens to hold a whitelist-shaped assertion.
    """
    package_root = pathlib.Path(authored_path(assembly_module)).parents[3]
    modules = sorted(package_root.rglob("*.py"))
    assert modules, f"no modules found under {package_root}; the walk is looking in the wrong place"
    marked = [
        str(path) for path in modules if "_mutmut_trampoline" in path.read_text(encoding="utf-8")
    ]
    assert marked == [], f"authored tree contains generated dispatchers: {marked}"


# ═══════════════════════════════════════════════════════════════════════════
# The reader.
# ═══════════════════════════════════════════════════════════════════════════


def test_a_file_outside_a_mutation_copy_is_returned_unchanged(tmp_path: pathlib.Path) -> None:
    """No `mutants` component means nothing to undo."""
    authored = tmp_path / "src" / "plain.py"
    authored.parent.mkdir(parents=True)
    authored.write_text(AUTHORED_BODY, encoding="utf-8")
    assert authored_path(_module_from(authored)) == authored.resolve()


def test_a_directory_named_mutants_with_no_twin_is_left_alone(tmp_path: pathlib.Path) -> None:
    """The redirect is conditional on the authored file EXISTING.

    A repository that genuinely keeps a directory called `mutants` is not a
    mutation copy, and stripping it would point at nothing. Guards the
    dangerous direction: silently reading the wrong file.
    """
    only = tmp_path / "mutants" / "real.py"
    only.parent.mkdir(parents=True)
    only.write_text(AUTHORED_BODY, encoding="utf-8")
    assert authored_path(_module_from(only)) == only.resolve()


def test_a_module_whose_file_is_gone_fails_loudly(tmp_path: pathlib.Path) -> None:
    """Never a silent fallback to whatever the interpreter happens to hold."""
    missing = tmp_path / "src" / "vanished.py"
    with pytest.raises(AuthoredSourceUnavailableError, match="not a file"):
        authored_path(_module_from(missing))


def test_the_parse_tree_comes_from_the_authored_text(tmp_path: pathlib.Path) -> None:
    """`authored_tree` is the parse of `authored_source`, not of the import."""
    authored = tmp_path / "src" / "pkg" / "t.py"
    authored.parent.mkdir(parents=True)
    authored.write_text(AUTHORED_BODY, encoding="utf-8")
    instrumented = tmp_path / "mutants" / "src" / "pkg" / "t.py"
    instrumented.parent.mkdir(parents=True)
    instrumented.write_text(AUTHORED_BODY + MUTMUT_DISPATCHER, encoding="utf-8")

    names = {
        node.name
        for node in authored_tree(_module_from(instrumented)).body
        if isinstance(node, ast.FunctionDef)
    }
    assert names == {"combine", "helper"}, f"parsed the wrong file: {sorted(names)}"


# ═══════════════════════════════════════════════════════════════════════════
# Function-level reads — the direction that fails SILENTLY.
# ═══════════════════════════════════════════════════════════════════════════


def test_a_function_is_found_by_name_in_the_authored_file(tmp_path: pathlib.Path) -> None:
    """mutmut renames `combine` to `x_combine__mutmut_orig` and binds the
    public name to the dispatcher, so `inspect.getsource(module.combine)`
    returns boilerplate. Asked for by name, the authored body comes back.
    """
    authored = tmp_path / "src" / "pkg" / "f.py"
    authored.parent.mkdir(parents=True)
    authored.write_text(AUTHORED_BODY, encoding="utf-8")
    instrumented = tmp_path / "mutants" / "src" / "pkg" / "f.py"
    instrumented.parent.mkdir(parents=True)
    instrumented.write_text(
        AUTHORED_BODY.replace("def combine(", "def x_combine__mutmut_orig(") + MUTMUT_DISPATCHER,
        encoding="utf-8",
    )
    body = authored_function_source(_module_from(instrumented), "combine")
    assert body.startswith("def combine(")
    assert "is not None" in body
    assert "MUTANT_UNDER_TEST" not in body


def test_a_nested_definition_never_shadows_the_one_asked_for(tmp_path: pathlib.Path) -> None:
    """`helper` defines an inner `combine`. `ast.walk` would return whichever
    it reached first; only top-level definitions count.
    """
    authored = tmp_path / "src" / "pkg" / "n.py"
    authored.parent.mkdir(parents=True)
    authored.write_text(AUTHORED_BODY, encoding="utf-8")
    body = authored_function_source(_module_from(authored), "combine")
    assert "is not None" in body, f"returned the nested definition instead: {body!r}"


def test_an_unknown_function_name_is_an_error_not_an_empty_string(
    tmp_path: pathlib.Path,
) -> None:
    """An assertion over `""` passes every check and proves nothing."""
    authored = tmp_path / "src" / "pkg" / "u.py"
    authored.parent.mkdir(parents=True)
    authored.write_text(AUTHORED_BODY, encoding="utf-8")
    with pytest.raises(AuthoredSourceUnavailableError, match="no top-level function named 'nope'"):
        authored_function_source(_module_from(authored), "nope")


# ═══════════════════════════════════════════════════════════════════════════
# The validator.
# ═══════════════════════════════════════════════════════════════════════════

PROCESS_RELATIVE_READERS = frozenset(
    {"getsource", "getfile", "getsourcefile", "getsourcelines", "findsource"}
)

# The canary feeds the validator one of each banned spelling: `inspect.
# getsource`, `inspect.getfile`, a `__file__` read next to its use, and a
# `__file__` handed to a helper — the indirection that defeated the first
# version of this guard. The canary also contains one LEGAL `__file__`
# assignment, which must NOT be counted.
BANNED_SPELLINGS_IN_THE_CANARY = 4

# A floor, not the count — new test files are expected. Its only job is to fail
# when the walk finds nothing, because a scan over an empty list passes.
FEWEST_TEST_FILES_THAT_CAN_BE_REAL = 40


def _reads_a_module_file_attribute(node: ast.AST) -> TypeGuard[ast.Attribute]:
    """Any READ of `<something>.__file__`.

    Deliberately wider than "a `__file__` that is immediately read from". The
    first version of this validator banned only `Path(x.__file__).read_text()`
    and was defeated the same afternoon by

        def top_level_imports(module_path: str) -> set[str]:
            source = pathlib.Path(module_path).read_text(...)
        ...
        imported = top_level_imports(reader.__file__)

    — the `__file__` and the read sat in different functions, so no
    single-expression rule could connect them, and `test_the_reader_imports_
    only_the_approved_stack` went on reading instrumented source. It reported
    `os`, `mutmut` and `inspect` as imports of `reader.py`.

    Chasing that across function boundaries needs dataflow analysis. Banning
    the attribute needs none, and there is nothing to lose by banning it:
    `authored_path` and `running_path` cover every legitimate use between
    them, and which one a caller wants is exactly the decision that must be
    made deliberately.

    Bare `__file__` — the test file's own — is an `ast.Name`, not an
    attribute, and stays legal. Assigning `module.__file__` on a constructed
    module is a `Store`, not a read, and stays legal.
    """
    return (
        isinstance(node, ast.Attribute)
        and node.attr == "__file__"
        and isinstance(node.ctx, ast.Load)
    )


def _test_files() -> list[pathlib.Path]:
    root = pathlib.Path(__file__).resolve().parent.parent
    return sorted(root.rglob("*.py"))


def test_no_test_reads_source_through_the_running_interpreter() -> None:
    """THE VALIDATOR. Every source read goes through `authored_source`.

    `inspect.getsource`, its siblings, and `<module>.__file__` all answer
    "what is loaded", never "what is written". Under mutation the loaded
    module is a rewrite, so a whitelist
    assertion turns red on mutmut's own code and a function-level assertion
    turns green against mutmut's boilerplate. Neither outcome is about this
    repository.
    """
    offenders: list[str] = []
    for path in _test_files():
        text = path.read_text(encoding="utf-8")
        for node in ast.walk(ast.parse(text)):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr in PROCESS_RELATIVE_READERS
            ):
                offenders.append(f"{path.name}:{node.lineno} inspect.{node.func.attr}(...)")
            elif _reads_a_module_file_attribute(node):
                offenders.append(f"{path.name}:{node.lineno} <module>.__file__")
    assert offenders == [], (
        "these read source through the running interpreter. Use "
        "`authored_source`/`authored_path` to assert about what we WROTE, or "
        "`running_path` to execute or inspect what is LOADED — but say which:\n  "
        + "\n  ".join(sorted(offenders))
    )


def test_the_validator_would_catch_the_pattern_it_bans() -> None:
    """HOLLOW-GATE DEFENCE. A validator that scans nothing exits 0 too.

    Feeds it both banned spellings and requires both to be seen. Without this,
    a typo in the attribute set would leave the guard reporting green forever.
    """
    banned = ast.parse(
        "import inspect, pathlib\n"
        "a = inspect.getsource(m)\n"
        "b = inspect.getfile(m)\n"
        "c = pathlib.Path(m.__file__).read_text()\n"
        "d = helper(m.__file__)\n"
        "m.__file__ = legal\n"
    )
    seen = [
        node
        for node in ast.walk(banned)
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr in PROCESS_RELATIVE_READERS
        )
        or _reads_a_module_file_attribute(node)
    ]
    assert len(seen) == BANNED_SPELLINGS_IN_THE_CANARY, (
        f"the validator missed a banned spelling; saw {len(seen)} of "
        f"{BANNED_SPELLINGS_IN_THE_CANARY}"
    )


def test_the_validator_looks_at_every_test_file() -> None:
    """A scan over an empty list passes. Pin the floor to the real count."""
    files = _test_files()
    assert len(files) >= FEWEST_TEST_FILES_THAT_CAN_BE_REAL, (
        f"only {len(files)} test files found; the walk is wrong"
    )
    assert pathlib.Path(__file__).resolve() in files


def test_no_test_derives_the_source_tree_from_its_own_location() -> None:
    """THE THIRD SPELLING. Banning `inspect.getsource` and `<module>.__file__`
    left one route open, and it cost a whole mutation run at `4fc7187`:

        REPO = pathlib.Path(__file__).resolve().parents[2]
        PACKAGE = REPO / "src" / "accountant_dad"

    No module object, no `inspect` call — just the test file asking where it
    is. Under mutation the test file itself lives in `mutants/`, so `PACKAGE`
    walks the instrumented copies.

    It survived because the two trees agreed on everything the reader asked.
    mutmut 3.7.0 ended that: its dispatcher imports `mutmut` at module scope,
    so `test_declared_dependencies` reported thirty-three modules "needing"
    mutmut, failed the stats phase, and left all 4097 mutants unscored.

    Bare `__file__` stays legal — a test locating its own fixtures is right to
    use it. Deriving the SOURCE TREE from it is what is banned; use
    `authored_repo_root()`.
    """
    offenders: list[str] = []
    for path in _test_files():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        rooted_in_own_location = {
            target.id
            for node in tree.body
            if isinstance(node, ast.Assign) and "__file__" in ast.unparse(node.value)
            for target in node.targets
            if isinstance(target, ast.Name)
        }
        if not rooted_in_own_location:
            continue
        for node in ast.walk(tree):
            if not (isinstance(node, ast.BinOp) and isinstance(node.op, ast.Div)):
                continue
            joined = ast.unparse(node)
            reaches_source = '"src"' in joined or "'src'" in joined
            if reaches_source and any(name in joined for name in rooted_in_own_location):
                # `A / "src" / "pkg"` is two nested BinOps and would report
                # the same line twice. A duplicated finding reads as two
                # defects and makes the count meaningless.
                finding = f"{path.name}:{node.lineno}"
                if not any(o.startswith(finding) for o in offenders):
                    offenders.append(f"{finding} {joined[:70]}")
    assert offenders == [], (
        "these derive the source tree from the test file's own location, which "
        "points into `mutants/` under mutation. Use `authored_repo_root()`:\n  "
        + "\n  ".join(sorted(offenders))
    )


def test_the_third_spelling_validator_catches_what_it_bans() -> None:
    """HOLLOW-GATE DEFENCE, both directions.

    The banned shape must be seen, and the legal one must NOT be — a validator
    that flags every `__file__` would be rejected on sight and quietly deleted.
    """
    banned = ast.parse(
        "import pathlib\n"
        "REPO = pathlib.Path(__file__).resolve().parents[2]\n"
        "PACKAGE = REPO / 'src' / 'accountant_dad'\n"
    )
    legal = ast.parse(
        "import pathlib\n"
        "HERE = pathlib.Path(__file__).parent\n"
        "FIXTURE = HERE / 'fixtures' / 'invoice.pdf'\n"
    )

    def offences(tree: ast.Module) -> int:
        roots = {
            t.id
            for n in tree.body
            if isinstance(n, ast.Assign) and "__file__" in ast.unparse(n.value)
            for t in n.targets
            if isinstance(t, ast.Name)
        }
        return len(
            {
                n.lineno
                for n in ast.walk(tree)
                if isinstance(n, ast.BinOp)
                and isinstance(n.op, ast.Div)
                and ("'src'" in ast.unparse(n) or '"src"' in ast.unparse(n))
                and any(r in ast.unparse(n) for r in roots)
            }
        )

    assert offences(banned) == 1, "the validator misses the shape that broke the mutation run"
    assert offences(legal) == 0, "the validator flags a test locating its own fixtures"
