name: performance

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  performance:
    name: performance
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - performance"
          exit 0
