name: quality

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - build"
          exit 0

  typecheck:
    name: typecheck
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - typecheck"
          exit 0

  lint:
    name: lint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - lint"
          exit 0

  docker-build:
    name: docker build
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - docker build"
          exit 0
