name: security

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - codeql"
          exit 1

  semgrep:
    name: semgrep
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - semgrep"
          exit 1

  secret-scan:
    name: secret scan
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - secret scan"
          exit 1

  dependency-scan:
    name: dependency scan
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: not implemented
        run: |
          echo "NOT IMPLEMENTED - dependency scan"
          exit 1
